/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "": {
    /** Getting Started */
    post: operations["getting-started"];
  };
  "/4/auth/request_token": {
    /** Create Request Token */
    post: operations["auth-create-request-token"];
  };
  "/4/auth/access_token": {
    /** Create Access Token */
    post: operations["auth-create-access-token"];
    /**
     * Logout
     * @description Log out of a session.
     */
    delete: operations["auth-logout"];
  };
  "/4/list/{list_id}": {
    /**
     * Details
     * @description Retrieve a list by id.
     */
    get: operations["list-details"];
    /**
     * Update
     * @description Update the details of a list.
     */
    put: operations["list-update"];
  };
  "/4/list": {
    /**
     * Create
     * @description Create a new list.
     */
    post: operations["list-create"];
  };
  "/4/list/{list_id}/clear": {
    /**
     * Clear
     * @description Clear all of the items on a list.
     */
    get: operations["list-clear"];
  };
  "/4/{list_id}": {
    /**
     * Delete
     * @description Delete a list.
     */
    delete: operations["list-delete"];
  };
  "/4/list/{list_id}/items": {
    /**
     * Update Items
     * @description Update an individual item on a list
     */
    put: operations["list-update-items"];
    /**
     * Add Items
     * @description Add items to a list.
     */
    post: operations["list-add-items"];
    /**
     * Remove Items
     * @description Remove items from a list
     */
    delete: operations["list-remove-items"];
  };
  "/4/list/{list_id}/item_status": {
    /**
     * Item Status
     * @description Check if an item is on a list.
     */
    get: operations["list-item-status"];
  };
  "/4/account/{account_object_id}/lists": {
    /**
     * Lists
     * @description Get all of the lists you've created.
     */
    get: operations["account-lists"];
  };
  "/4/account/{account_object_id}/movie/favorites": {
    /**
     * Favorite Movies
     * @description Get a user's list of favourite movies.
     */
    get: operations["account-favorite-movies"];
  };
  "/4/account/{account_object_id}/tv/favorites": {
    /**
     * Favorite TV Shows
     * @description Get a user's list of favourite TV shows.
     */
    get: operations["account-favorite-tv"];
  };
  "/4/account/{account_object_id}/tv/recommendations": {
    /**
     * Recommended TV Shows
     * @description Get a user's list of recommended TV shows.
     */
    get: operations["account-tv-recommendations"];
  };
  "/4/account/{account_object_id}/movie/recommendations": {
    /**
     * Recommended Movies
     * @description Get a user's list of recommended movies.
     */
    get: operations["account-movie-recommendations"];
  };
  "/4/account/{account_object_id}/movie/watchlist": {
    /**
     * Watchlist Movies
     * @description Get a user's movie watchlist.
     */
    get: operations["account-movie-watchlist"];
  };
  "/4/account/{account_object_id}/tv/watchlist": {
    /**
     * Watchlist TV Shows
     * @description Get a user's TV watchlist.
     */
    get: operations["account-tv-watchlist"];
  };
  "/4/account/{account_object_id}/movie/rated": {
    /**
     * Rated Movies
     * @description Get a user's rated movies.
     */
    get: operations["account-rated-movies"];
  };
  "/4/account/{account_object_id}/tv/rated": {
    /**
     * Rated TV Shows
     * @description Get a user's rated TV shows.
     */
    get: operations["account-rated-tv"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Getting Started */
  "getting-started": {
  };
  /** Create Request Token */
  "auth-create-request-token": {
    requestBody?: {
      content: {
        "application/json": {
          /** Format: json */
          RAW_BODY: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /** @example Success. */
            status_message?: string;
            /** @example eyJhbGciOiJIfsISNiIaInR5cCI6IkpXVCJ9.eyJuYmYiOjE0NzIwNTQ1ODEsInZlcnNpb24iOjEsImV4zCI6MTQ3MjA1NTQ4MSwiYXXkIjoiM2Y4Nzg1N2JlMjA5ZDM1MTk4MzNiMzAwYTEzZDBlMqIiLCJzY29wZXMiOlsicGVuZGluZ19yZXF1ZXN0X3Rva2VuIl0sImp0aSI6Nd0.e0t83AUvwywXPBb-hSAY_J_y4TjcwA0w98GhCCQM1dA */
            request_token?: string;
            /**
             * @default true
             * @example true
             */
            success?: boolean;
            /**
             * @default 0
             * @example 1
             */
            status_code?: number;
          };
        };
      };
    };
  };
  /** Create Access Token */
  "auth-create-access-token": {
    requestBody?: {
      content: {
        "application/json": {
          /** Format: json */
          RAW_BODY: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /** @example 4bc8892a017a3c0z92001001 */
            account_id?: string;
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCIdIkpXVCJ9.eyJuYmYiOjE0ODM1NzM4MzUsInZlcnNpb24iOjEsInN1YiI6IjRiYzg4OTJhMDE3YTNjMGY5MjAwMDAwMiIsImF1ZCI6IlNmODc4NTdiZTIwOWQzNTE5ODMzYjMwMGExM2QwZTEyIiwic2NvcGVzIjpbImFwaV9yZWFkIiwiYXBpX3dyaXRlIl0sImp0aSI6Ijg4In0.b76OiEs10gdp9oNOoGpBJ94nO9Zi17Y7SvAXJQW8nH2 */
            access_token?: string;
            /**
             * @default true
             * @example true
             */
            success?: boolean;
            /** @example Success. */
            status_message?: string;
            /**
             * @default 0
             * @example 1
             */
            status_code?: number;
          };
        };
      };
    };
  };
  /**
   * Logout
   * @description Log out of a session.
   */
  "auth-logout": {
    requestBody?: {
      content: {
        "application/json": {
          /** Format: json */
          RAW_BODY: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /** @example The item/record was deleted successfully. */
            status_message?: string;
            /**
             * @default true
             * @example true
             */
            success?: boolean;
            /**
             * @default 0
             * @example 13
             */
            status_code?: number;
          };
        };
      };
    };
  };
  /**
   * Details
   * @description Retrieve a list by id.
   */
  "list-details": {
    parameters: {
      query?: {
        language?: string;
        page?: number;
      };
      path: {
        list_id: number;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 6.7
             */
            average_rating?: number;
            /** @example /kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg */
            backdrop_path?: string;
            results?: {
                /**
                 * @default true
                 * @example false
                 */
                adult?: boolean;
                /** @example /hFtJz4TvoiJJcw2ZOMdhK22aU9P.jpg */
                backdrop_path?: string;
                /**
                 * @default 0
                 * @example 617127
                 */
                id?: number;
                /** @example Blade */
                title?: string;
                /** @example en */
                original_language?: string;
                /** @example Blade */
                original_title?: string;
                /** @example A film set in the Marvel Cinematic Universe (MCU) based on the Marvel Comics character of the same name. */
                overview?: string;
                /** @example /fKqA4rgVJwrM7Gb3tQ9TGHnu8Tr.jpg */
                poster_path?: string;
                /** @example movie */
                media_type?: string;
                genre_ids?: number[];
                /**
                 * @default 0
                 * @example 20.856
                 */
                popularity?: number;
                /** @example 2025-02-12 */
                release_date?: string;
                /**
                 * @default true
                 * @example false
                 */
                video?: boolean;
                /**
                 * @default 0
                 * @example 0
                 */
                vote_average?: number;
                /**
                 * @default 0
                 * @example 0
                 */
                vote_count?: number;
              }[];
            comments?: {
              "movie:617127"?: unknown;
              "movie:986056"?: unknown;
              "movie:822119"?: unknown;
              "movie:533535"?: unknown;
              "movie:609681"?: unknown;
              "movie:447365"?: unknown;
              "movie:640146"?: unknown;
              "movie:505642"?: unknown;
              "movie:616037"?: unknown;
              "movie:453395"?: unknown;
              "movie:634649"?: unknown;
              "movie:524434"?: unknown;
              "movie:566525"?: unknown;
              "movie:497698"?: unknown;
              "movie:429617"?: unknown;
              "movie:299534"?: unknown;
              "movie:299537"?: unknown;
              "movie:363088"?: unknown;
              "movie:299536"?: unknown;
              "movie:284054"?: unknown;
            };
            created_by?: {
              /** @example /xy44UvpbTgzs9kWmp4C3fEaCl5h.png */
              avatar_path?: string;
              /** @example c9e9fc152ee756a900db85757c29815d */
              gravatar_hash?: string;
              /** @example 4bc8892a017a3c0f92000002 */
              id?: string;
              /** @example Travis Bell */
              name?: string;
              /** @example travisbell */
              username?: string;
            };
            /** @example The idea behind this list is to collect the live action comic book movies from within the Marvel franchise. */
            description?: string;
            /**
             * @default 0
             * @example 1
             */
            id?: number;
            /** @example US */
            iso_3166_1?: string;
            /** @example en */
            iso_639_1?: string;
            /**
             * @default 0
             * @example 69
             */
            item_count?: number;
            /** @example The Marvel Universe */
            name?: string;
            object_ids?: Record<string, never>;
            /**
             * @default 0
             * @example 1
             */
            page?: number;
            /** @example /coJVIUEOToAEGViuhclM7pXC75R.jpg */
            poster_path?: string;
            /**
             * @default true
             * @example true
             */
            public?: boolean;
            /**
             * @default 0
             * @example 40672159319
             */
            revenue?: number;
            /**
             * @default 0
             * @example 8070
             */
            runtime?: number;
            /** @example primary_release_date.desc */
            sort_by?: string;
            /**
             * @default 0
             * @example 4
             */
            total_pages?: number;
            /**
             * @default 0
             * @example 69
             */
            total_results?: number;
          };
        };
      };
    };
  };
  /**
   * Update
   * @description Update the details of a list.
   */
  "list-update": {
    parameters: {
      path: {
        list_id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          /** Format: json */
          RAW_BODY: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /** @example The item/record was updated successfully. */
            status_message?: string;
            /**
             * @default true
             * @example true
             */
            success?: boolean;
            /**
             * @default 0
             * @example 12
             */
            status_code?: number;
          };
        };
      };
    };
  };
  /**
   * Create
   * @description Create a new list.
   */
  "list-create": {
    requestBody?: {
      content: {
        "application/json": {
          /** Format: json */
          RAW_BODY: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /** @example The item/record was created successfully. */
            status_message?: string;
            /**
             * @default 0
             * @example 5854
             */
            id?: number;
            /**
             * @default true
             * @example true
             */
            success?: boolean;
            /**
             * @default 0
             * @example 1
             */
            status_code?: number;
          };
        };
      };
    };
  };
  /**
   * Clear
   * @description Clear all of the items on a list.
   */
  "list-clear": {
    parameters: {
      path: {
        list_id: number;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 1
             */
            items_deleted?: number;
            /** @example Success. */
            status_message?: string;
            /**
             * @default 0
             * @example 10
             */
            id?: number;
            /**
             * @default 0
             * @example 1
             */
            status_code?: number;
            /**
             * @default true
             * @example true
             */
            success?: boolean;
          };
        };
      };
    };
  };
  /**
   * Delete
   * @description Delete a list.
   */
  "list-delete": {
    parameters: {
      path: {
        list_id: number;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /** @example The item/record was deleted successfully. */
            status_message?: string;
            /**
             * @default true
             * @example true
             */
            success?: boolean;
            /**
             * @default 0
             * @example 13
             */
            status_code?: number;
          };
        };
      };
    };
  };
  /**
   * Update Items
   * @description Update an individual item on a list
   */
  "list-update-items": {
    requestBody?: {
      content: {
        "application/json": {
          /** Format: json */
          RAW_BODY: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /** @example Success. */
            status_message?: string;
            results?: {
                /** @example movie */
                media_type?: string;
                /**
                 * @default 0
                 * @example 194662
                 */
                media_id?: number;
                /**
                 * @default true
                 * @example true
                 */
                success?: boolean;
              }[];
            /**
             * @default true
             * @example true
             */
            success?: boolean;
            /**
             * @default 0
             * @example 1
             */
            status_code?: number;
          };
        };
      };
    };
  };
  /**
   * Add Items
   * @description Add items to a list.
   */
  "list-add-items": {
    parameters: {
      path: {
        list_id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          /** Format: json */
          RAW_BODY: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /** @example Success. */
            status_message?: string;
            results?: {
                /** @example movie */
                media_type?: string;
                /**
                 * @default 0
                 * @example 550
                 */
                media_id?: number;
                /**
                 * @default true
                 * @example false
                 */
                success?: boolean;
              }[];
            /**
             * @default true
             * @example true
             */
            success?: boolean;
            /**
             * @default 0
             * @example 1
             */
            status_code?: number;
          };
        };
      };
    };
  };
  /**
   * Remove Items
   * @description Remove items from a list
   */
  "list-remove-items": {
    parameters: {
      path: {
        list_id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          /** Format: json */
          RAW_BODY: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /** @example Success. */
            status_message?: string;
            results?: {
                /** @example movie */
                media_type?: string;
                /**
                 * @default 0
                 * @example 194662
                 */
                media_id?: number;
                /**
                 * @default true
                 * @example true
                 */
                success?: boolean;
              }[];
            /**
             * @default true
             * @example true
             */
            success?: boolean;
            /**
             * @default 0
             * @example 1
             */
            status_code?: number;
          };
        };
      };
    };
  };
  /**
   * Item Status
   * @description Check if an item is on a list.
   */
  "list-item-status": {
    parameters: {
      query: {
        media_id: number;
        media_type: "" | "movie" | "tv";
      };
      path: {
        list_id: number;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /** @example movie */
            media_type?: string;
            /**
             * @default true
             * @example true
             */
            success?: boolean;
            /** @example Success. */
            status_message?: string;
            /**
             * @default 0
             * @example 1
             */
            id?: number;
            /**
             * @default 0
             * @example 99861
             */
            media_id?: number;
            /**
             * @default 0
             * @example 1
             */
            status_code?: number;
          };
        };
      };
    };
  };
  /**
   * Lists
   * @description Get all of the lists you've created.
   */
  "account-lists": {
    parameters: {
      query?: {
        page?: number;
      };
      path: {
        account_object_id: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 1
             */
            page?: number;
            results?: {
                /** @example 4bc8892a017a3c0f92000002 */
                account_object_id?: string;
                /**
                 * @default 0
                 * @example 0
                 */
                adult?: number;
                /**
                 * @default 0
                 * @example 7.90183
                 */
                average_rating?: number;
                /** @example 2019-08-27 15:13:15 */
                created_at?: string;
                /** @example */
                description?: string;
                /**
                 * @default 0
                 * @example 0
                 */
                featured?: number;
                /**
                 * @default 0
                 * @example 120174
                 */
                id?: number;
                /** @example US */
                iso_3166_1?: string;
                /** @example en */
                iso_639_1?: string;
                /** @example Test Alpha Sort */
                name?: string;
                /**
                 * @default 0
                 * @example 6
                 */
                number_of_items?: number;
                /**
                 * @default 0
                 * @example 0
                 */
                public?: number;
                /** @example 586453267 */
                revenue?: string;
                /**
                 * @default 0
                 * @example 644
                 */
                runtime?: number;
                /**
                 * @default 0
                 * @example 7
                 */
                sort_by?: number;
                /** @example 2023-05-05 16:49:11 */
                updated_at?: string;
              }[];
            /**
             * @default 0
             * @example 2
             */
            total_pages?: number;
            /**
             * @default 0
             * @example 25
             */
            total_results?: number;
          };
        };
      };
    };
  };
  /**
   * Favorite Movies
   * @description Get a user's list of favourite movies.
   */
  "account-favorite-movies": {
    parameters: {
      query?: {
        page?: number;
        language?: string;
      };
      path: {
        account_object_id: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 1
             */
            page?: number;
            results?: {
                /**
                 * @default true
                 * @example false
                 */
                adult?: boolean;
                /** @example /se5Hxz7PArQZOG3Nx2bpfOhLhtV.jpg */
                backdrop_path?: string;
                genre_ids?: number[];
                /**
                 * @default 0
                 * @example 9806
                 */
                id?: number;
                /** @example en */
                original_language?: string;
                /** @example The Incredibles */
                original_title?: string;
                /** @example Bob Parr has given up his superhero days to log in time as an insurance adjuster and raise his three children with his formerly heroic wife in suburbia. But when he receives a mysterious assignment, it's time to get back into costume. */
                overview?: string;
                /**
                 * @default 0
                 * @example 67.887
                 */
                popularity?: number;
                /** @example /2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg */
                poster_path?: string;
                /** @example 2004-10-27 */
                release_date?: string;
                /** @example The Incredibles */
                title?: string;
                /**
                 * @default true
                 * @example false
                 */
                video?: boolean;
                /**
                 * @default 0
                 * @example 7.702
                 */
                vote_average?: number;
                /**
                 * @default 0
                 * @example 16188
                 */
                vote_count?: number;
              }[];
            /**
             * @default 0
             * @example 4
             */
            total_pages?: number;
            /**
             * @default 0
             * @example 80
             */
            total_results?: number;
          };
        };
      };
    };
  };
  /**
   * Favorite TV Shows
   * @description Get a user's list of favourite TV shows.
   */
  "account-favorite-tv": {
    parameters: {
      query?: {
        page?: number;
        language?: string;
      };
      path: {
        account_object_id: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 1
             */
            page?: number;
            results?: {
                /**
                 * @default true
                 * @example false
                 */
                adult?: boolean;
                /** @example /bsNm9z2TJfe0WO3RedPGWQ8mG1X.jpg */
                backdrop_path?: string;
                genre_ids?: number[];
                /**
                 * @default 0
                 * @example 1396
                 */
                id?: number;
                origin_country?: string[];
                /** @example en */
                original_language?: string;
                /** @example Breaking Bad */
                original_name?: string;
                /** @example When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime. */
                overview?: string;
                /**
                 * @default 0
                 * @example 255.118
                 */
                popularity?: number;
                /** @example /ggFHVNu6YYI5L9pCfOacjizRGt.jpg */
                poster_path?: string;
                /** @example 2008-01-20 */
                first_air_date?: string;
                /** @example Breaking Bad */
                name?: string;
                /**
                 * @default 0
                 * @example 8.879
                 */
                vote_average?: number;
                /**
                 * @default 0
                 * @example 11625
                 */
                vote_count?: number;
              }[];
            /**
             * @default 0
             * @example 4
             */
            total_pages?: number;
            /**
             * @default 0
             * @example 68
             */
            total_results?: number;
          };
        };
      };
    };
  };
  /**
   * Recommended TV Shows
   * @description Get a user's list of recommended TV shows.
   */
  "account-tv-recommendations": {
    parameters: {
      query?: {
        page?: number;
        language?: string;
      };
      path: {
        account_object_id: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 1
             */
            page?: number;
            results?: {
                /**
                 * @default true
                 * @example false
                 */
                adult?: boolean;
                /** @example /7bsHAsS1RDtslictkApeb7cedLL.jpg */
                backdrop_path?: string;
                /**
                 * @default 0
                 * @example 152483
                 */
                id?: number;
                /** @example The Boys Presents: Diabolical */
                name?: string;
                /** @example en */
                original_language?: string;
                /** @example The Boys Presents: Diabolical */
                original_name?: string;
                /** @example From some of the most unhinged and maniacal minds in Hollywood today comes this animated anthology series, a collection of irreverent and emotionally shocking animated short films. Each episode plunges elbow-deep into unseen crevices of The Boys Universe. */
                overview?: string;
                /** @example /kZKfZWwFOAicgoKS2IO7oM1GuHZ.jpg */
                poster_path?: string;
                /** @example tv */
                media_type?: string;
                genre_ids?: number[];
                /**
                 * @default 0
                 * @example 24.596
                 */
                popularity?: number;
                /** @example 2022-03-03 */
                first_air_date?: string;
                /**
                 * @default 0
                 * @example 7.201
                 */
                vote_average?: number;
                /**
                 * @default 0
                 * @example 214
                 */
                vote_count?: number;
                origin_country?: string[];
              }[];
            /**
             * @default 0
             * @example 4
             */
            total_pages?: number;
            /**
             * @default 0
             * @example 80
             */
            total_results?: number;
          };
        };
      };
    };
  };
  /**
   * Recommended Movies
   * @description Get a user's list of recommended movies.
   */
  "account-movie-recommendations": {
    parameters: {
      query?: {
        page?: number;
        language?: string;
      };
      path: {
        account_object_id: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 1
             */
            page?: number;
            results?: {
                /**
                 * @default true
                 * @example false
                 */
                adult?: boolean;
                /** @example /9sfVyE3sP2dkCwDyV7UlYP5TAAR.jpg */
                backdrop_path?: string;
                /**
                 * @default 0
                 * @example 823754
                 */
                id?: number;
                /** @example Bo Burnham: Inside */
                title?: string;
                /** @example en */
                original_language?: string;
                /** @example Bo Burnham: Inside */
                original_title?: string;
                /** @example Stuck in COVID-19 lockdown, US comedian and musician Bo Burnham attempts to stay sane and happy by writing, shooting and performing a one-man comedy special. */
                overview?: string;
                /** @example /ku1UvTWYvhFQbSesOD6zteY7bXT.jpg */
                poster_path?: string;
                /** @example movie */
                media_type?: string;
                genre_ids?: number[];
                /**
                 * @default 0
                 * @example 11.904
                 */
                popularity?: number;
                /** @example 2021-07-22 */
                release_date?: string;
                /**
                 * @default true
                 * @example false
                 */
                video?: boolean;
                /**
                 * @default 0
                 * @example 8.178
                 */
                vote_average?: number;
                /**
                 * @default 0
                 * @example 352
                 */
                vote_count?: number;
              }[];
            /**
             * @default 0
             * @example 4
             */
            total_pages?: number;
            /**
             * @default 0
             * @example 80
             */
            total_results?: number;
          };
        };
      };
    };
  };
  /**
   * Watchlist Movies
   * @description Get a user's movie watchlist.
   */
  "account-movie-watchlist": {
    parameters: {
      query?: {
        page?: number;
        language?: string;
      };
      path: {
        account_object_id: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 1
             */
            page?: number;
            results?: {
                /**
                 * @default true
                 * @example false
                 */
                adult?: boolean;
                /** @example /9sfVyE3sP2dkCwDyV7UlYP5TAAR.jpg */
                backdrop_path?: string;
                /**
                 * @default 0
                 * @example 823754
                 */
                id?: number;
                /** @example Bo Burnham: Inside */
                title?: string;
                /** @example en */
                original_language?: string;
                /** @example Bo Burnham: Inside */
                original_title?: string;
                /** @example Stuck in COVID-19 lockdown, US comedian and musician Bo Burnham attempts to stay sane and happy by writing, shooting and performing a one-man comedy special. */
                overview?: string;
                /** @example /ku1UvTWYvhFQbSesOD6zteY7bXT.jpg */
                poster_path?: string;
                /** @example movie */
                media_type?: string;
                genre_ids?: number[];
                /**
                 * @default 0
                 * @example 11.904
                 */
                popularity?: number;
                /** @example 2021-07-22 */
                release_date?: string;
                /**
                 * @default true
                 * @example false
                 */
                video?: boolean;
                /**
                 * @default 0
                 * @example 8.178
                 */
                vote_average?: number;
                /**
                 * @default 0
                 * @example 352
                 */
                vote_count?: number;
              }[];
            /**
             * @default 0
             * @example 4
             */
            total_pages?: number;
            /**
             * @default 0
             * @example 80
             */
            total_results?: number;
          };
        };
      };
    };
  };
  /**
   * Watchlist TV Shows
   * @description Get a user's TV watchlist.
   */
  "account-tv-watchlist": {
    parameters: {
      query?: {
        page?: number;
        language?: string;
      };
      path: {
        account_object_id: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 1
             */
            page?: number;
            results?: {
                /**
                 * @default true
                 * @example false
                 */
                adult?: boolean;
                /** @example /7bsHAsS1RDtslictkApeb7cedLL.jpg */
                backdrop_path?: string;
                /**
                 * @default 0
                 * @example 152483
                 */
                id?: number;
                /** @example The Boys Presents: Diabolical */
                name?: string;
                /** @example en */
                original_language?: string;
                /** @example The Boys Presents: Diabolical */
                original_name?: string;
                /** @example From some of the most unhinged and maniacal minds in Hollywood today comes this animated anthology series, a collection of irreverent and emotionally shocking animated short films. Each episode plunges elbow-deep into unseen crevices of The Boys Universe. */
                overview?: string;
                /** @example /kZKfZWwFOAicgoKS2IO7oM1GuHZ.jpg */
                poster_path?: string;
                /** @example tv */
                media_type?: string;
                genre_ids?: number[];
                /**
                 * @default 0
                 * @example 24.596
                 */
                popularity?: number;
                /** @example 2022-03-03 */
                first_air_date?: string;
                /**
                 * @default 0
                 * @example 7.201
                 */
                vote_average?: number;
                /**
                 * @default 0
                 * @example 214
                 */
                vote_count?: number;
                origin_country?: string[];
              }[];
            /**
             * @default 0
             * @example 4
             */
            total_pages?: number;
            /**
             * @default 0
             * @example 80
             */
            total_results?: number;
          };
        };
      };
    };
  };
  /**
   * Rated Movies
   * @description Get a user's rated movies.
   */
  "account-rated-movies": {
    parameters: {
      query?: {
        page?: number;
        language?: string;
      };
      path: {
        account_object_id: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 1
             */
            page?: number;
            results?: {
                /**
                 * @default true
                 * @example false
                 */
                adult?: boolean;
                /** @example /dUVbWINfRMGojGZRcO6GF1Z2nV8.jpg */
                backdrop_path?: string;
                genre_ids?: number[];
                /**
                 * @default 0
                 * @example 120
                 */
                id?: number;
                /** @example en */
                original_language?: string;
                /** @example The Lord of the Rings: The Fellowship of the Ring */
                original_title?: string;
                /** @example Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed. */
                overview?: string;
                /**
                 * @default 0
                 * @example 79.298
                 */
                popularity?: number;
                /** @example /6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg */
                poster_path?: string;
                /** @example 2001-12-18 */
                release_date?: string;
                /** @example The Lord of the Rings: The Fellowship of the Ring */
                title?: string;
                /**
                 * @default true
                 * @example false
                 */
                video?: boolean;
                /**
                 * @default 0
                 * @example 8.4
                 */
                vote_average?: number;
                /**
                 * @default 0
                 * @example 22626
                 */
                vote_count?: number;
                account_rating?: {
                  /** @example 2012-02-15T15:18:04.000Z */
                  created_at?: string;
                  /**
                   * @default 0
                   * @example 8
                   */
                  value?: number;
                };
              }[];
            /**
             * @default 0
             * @example 47
             */
            total_pages?: number;
            /**
             * @default 0
             * @example 940
             */
            total_results?: number;
          };
        };
      };
    };
  };
  /**
   * Rated TV Shows
   * @description Get a user's rated TV shows.
   */
  "account-rated-tv": {
    parameters: {
      query?: {
        page?: number;
        language?: string;
      };
      path: {
        account_object_id: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": {
            /**
             * @default 0
             * @example 1
             */
            page?: number;
            results?: {
                /**
                 * @default true
                 * @example false
                 */
                adult?: boolean;
                /** @example /2yZXtM2Kky1Sy0kachbDlwybl3y.jpg */
                backdrop_path?: string;
                genre_ids?: number[];
                /**
                 * @default 0
                 * @example 1705
                 */
                id?: number;
                origin_country?: string[];
                /** @example en */
                original_language?: string;
                /** @example Fringe */
                original_name?: string;
                /** @example FBI Special Agent Olivia Dunham, brilliant but formerly institutionalized scientist Walter Bishop and his scheming, reluctant son Peter uncover a deadly mystery involving a series of unbelievable events and realize they may be a part of a larger, more disturbing pattern that blurs the line between science fiction and technology. */
                overview?: string;
                /**
                 * @default 0
                 * @example 145.5
                 */
                popularity?: number;
                /** @example /sY9hg5dLJ93RJOyKEiu1nAtBRND.jpg */
                poster_path?: string;
                /** @example 2008-09-09 */
                first_air_date?: string;
                /** @example Fringe */
                name?: string;
                /**
                 * @default 0
                 * @example 8.11
                 */
                vote_average?: number;
                /**
                 * @default 0
                 * @example 2053
                 */
                vote_count?: number;
                account_rating?: {
                  /** @example 2013-10-10T21:03:56.499Z */
                  created_at?: string;
                  /**
                   * @default 0
                   * @example 9
                   */
                  value?: number;
                };
              }[];
            /**
             * @default 0
             * @example 15
             */
            total_pages?: number;
            /**
             * @default 0
             * @example 291
             */
            total_results?: number;
          };
        };
      };
    };
  };
}
