// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.5
// source: reiverr-plugin.proto

/* eslint-disable */
import { Observable } from "rxjs";

export const protobufPackage = "aleksilassila.reiverr.plugin.v1";

export interface Empty {
}

export interface PluginInfo {
  name: string;
  apiVersion: string;
  description: string;
  streamingSupported: boolean;
  cataloguesSupported: boolean;
}

export interface StreamablesRequest {
  title: string;
  season?: number | undefined;
  episode?: number | undefined;
  runtimeMinutes?: number | undefined;
  tmdbId?: string | undefined;
  imdbId?:
    | string
    | undefined;
  /** optional string media_type = 6; // "movie" or "series" */
  tvdbId?: string | undefined;
}

export interface StreamablesResponse {
  items: StreamableItem[];
}

export interface StreamableItem {
  id: string;
  label: string;
  quality?: string | undefined;
  source?: string | undefined;
  language?: string | undefined;
  releaseGroup?: string | undefined;
  size?: string | undefined;
  bitrate?: string | undefined;
}

export interface StreamRequest {
  id: string;
}

export interface StreamResponse {
  videoTracks: VideoTrack[];
  subtitleTracks: SubtitleTrack[];
}

export interface VideoTrack {
  label: string;
  url: string;
  /** "direct", "hls", "dash" */
  type: string;
  /**
   * optional string quality = 4;
   * optional string codec = 5;
   * optional int32 bitrate = 6;
   */
  lang?: string | undefined;
}

export interface SubtitleTrack {
  label: string;
  url: string;
  lang: string;
  /** "subtitles", "captions", "descriptions" */
  kind: string;
}

export interface CataloguesRequest {
}

export interface CataloguesResponse {
  catalogues: CatalogueInfo[];
}

export interface CatalogueInfo {
  id: string;
  label: string;
  orderOptions: OrderOption[];
}

export interface OrderOption {
  label: string;
  value: string;
  /** Define for direction grouping */
  direction?: string | undefined;
}

export interface CatalogueRequest {
  catalogueId: string;
  /** Referes to OrderOption.value */
  order?:
    | string
    | undefined;
  /**
   * PaginationParams pagination = 2;
   * optional string order = 3;
   * optional string direction = 4;
   */
  pagination?: PaginationParams | undefined;
}

export interface CatalogueResponse {
  /**
   * int32 total = 2;
   * int32 page = 3;
   * int32 items_per_page = 4;
   */
  items: CatalogueItem[];
}

export interface CatalogueItem {
  id: string;
  label: string;
  /** "movie" or "series" */
  mediaType: string;
  tmdbId?: string | undefined;
  posterUrl?: string | undefined;
  backdropUrl?: string | undefined;
}

export interface PaginationParams {
  /** 1-based page number */
  page: number;
  itemsPerPage: number;
}

/** Plugin Service - handles plugin metadata and configuration */
export interface PluginService {
  /** Get plugin metadata and version */
  GetInfo(request: Empty): Observable<PluginInfo>;
}

/** Media Source Provider Service - handles user-specific requests */
export interface PluginMediaService {
  /** Get a list of available streamables */
  GetStreamables(request: StreamablesRequest): Observable<StreamablesResponse>;
  /** Get a link to a streamable - on the plugin side, this can create a transcoding session for example */
  GetStream(request: StreamRequest): Observable<StreamResponse>;
}

/** Catalogue Provider Service - handles library catalogues */
export interface PluginCatalogueService {
  /** Get what catalogues are available */
  GetCatalogues(request: CataloguesRequest): Observable<CataloguesResponse>;
  /** Get everything in a catalogue - e.g. all movies or all series */
  GetCatalogue(request: CatalogueRequest): Observable<CatalogueResponse>;
}

/** Management Profile Service - NEW for monitoring/management profiles */
export interface ManagementProfileService {
}
