/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/users": {
    get: operations["UsersController_findAll"];
    post: operations["UsersController_create"];
  };
  "/users/{id}": {
    get: operations["UsersController_findById"];
    put: operations["UsersController_update"];
    delete: operations["UsersController_deleteUser"];
  };
  "/auth": {
    post: operations["AuthController_signIn"];
  };
  "/my-list": {
    get: operations["MyListController_getMyList"];
  };
  "/my-list/{tmdbId}": {
    post: operations["MyListController_addToMyList"];
    delete: operations["MyListController_removeFromMyList"];
  };
  "/titles/library": {
    get: operations["TitlesController_getLibrary"];
  };
  "/titles/continue-watching": {
    get: operations["TitlesController_getContinueWatching"];
  };
  "/titles/{tmdbId}": {
    get: operations["TitlesController_getTitle"];
    put: operations["TitlesController_updateTitle"];
  };
  "/titles/progress/{tmdbId}": {
    put: operations["TitlesController_updateProgress"];
  };
  "/": {
    get: operations["AppController_getHello"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SonarrSettings: {
      apiKey: string;
      baseUrl: string;
      qualityProfileId: number;
      rootFolderPath: string;
      languageProfileId: number;
    };
    RadarrSettings: {
      apiKey: string;
      baseUrl: string;
      qualityProfileId: number;
      rootFolderPath: string;
    };
    JellyfinSettings: {
      apiKey: string;
      baseUrl: string;
      userId: string;
    };
    PeerflixSettings: {
      baseUrl: string;
    };
    TmdbSettings: {
      sessionId: string;
      userId: string;
      libraryListId: string;
    };
    Settings: {
      autoplayTrailers: boolean;
      language: string;
      animationDuration: number;
      sonarr: components["schemas"]["SonarrSettings"];
      radarr: components["schemas"]["RadarrSettings"];
      jellyfin: components["schemas"]["JellyfinSettings"];
      peerflix: components["schemas"]["PeerflixSettings"];
      tmdb: components["schemas"]["TmdbSettings"];
    };
    MyListItemDto: {
      id: string;
      tmdbId: number;
    };
    UserDto: {
      id: string;
      name: string;
      isAdmin: boolean;
      onboardingDone?: boolean;
      settings: components["schemas"]["Settings"];
      profilePicture: string;
      myList: components["schemas"]["MyListItemDto"][];
    };
    CreateUserDto: {
      name: string;
      password: string;
      isAdmin: boolean;
      profilePicture?: string;
    };
    UpdateUserDto: {
      name?: string;
      password?: string;
      isAdmin?: boolean;
      onboardingDone?: boolean;
      settings?: components["schemas"]["Settings"];
      profilePicture?: string;
      oldPassword?: string;
    };
    SignInDto: {
      name: string;
      password: string;
    };
    SignInResponse: {
      accessToken: string;
      user: components["schemas"]["UserDto"];
    };
    Title: {
      id?: string;
      tmdbId: number;
      /** @enum {string} */
      type: "movie" | "series";
      upNext?: boolean;
      isInLibrary?: boolean;
      watched?: boolean;
      media?: components["schemas"]["Media"][];
    };
    Media: {
      id?: string;
      seasonNumber?: number;
      episodeNumber?: number;
      progress?: number;
      watched?: boolean;
      title: components["schemas"]["Title"];
    };
    TitleDto: {
      id?: string;
      tmdbId: number;
      /** @enum {string} */
      type: "movie" | "series";
      upNext?: boolean;
      isInLibrary?: boolean;
      watched?: boolean;
      media?: components["schemas"]["Media"][];
    };
    ContinueWatchingDto: {
      nextEpisode?: components["schemas"]["Media"] | null;
      title: components["schemas"]["Title"];
    };
    UpdateTitleDto: {
      /** @enum {string} */
      type?: "movie" | "series";
      upNext?: boolean;
      isInLibrary?: boolean;
      watched?: boolean;
      media?: components["schemas"]["Media"][];
    };
    UpdateProgressDto: {
      progress?: number;
      watched?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  UsersController_findAll: {
    responses: {
      /** @description All users found */
      200: {
        content: {
          "application/json": components["schemas"]["UserDto"][];
        };
      };
    };
  };
  UsersController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      /** @description User created */
      200: {
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      400: {
        content: {
          "application/json": {
            /** @example 400 */
            statusCode: number;
            /** @example Bad Request */
            message: string;
            /** @example Bad Request */
            error?: string;
          };
        };
      };
      401: {
        content: {
          "application/json": {
            /** @example 401 */
            statusCode: number;
            /** @example Unauthorized */
            message: string;
            /** @example Unauthorized */
            error?: string;
          };
        };
      };
    };
  };
  UsersController_findById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description User found */
      200: {
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      404: {
        content: {
          "application/json": {
            /** @example 404 */
            statusCode: number;
            /** @example Not Found */
            message: string;
            /** @example Not Found */
            error?: string;
          };
        };
      };
    };
  };
  UsersController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserDto"];
      };
    };
    responses: {
      /** @description User updated */
      200: {
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      404: {
        content: {
          "application/json": {
            /** @example 404 */
            statusCode: number;
            /** @example Not Found */
            message: string;
            /** @example Not Found */
            error?: string;
          };
        };
      };
    };
  };
  UsersController_deleteUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description User deleted */
      200: {
        content: never;
      };
      404: {
        content: {
          "application/json": {
            /** @example 404 */
            statusCode: number;
            /** @example Not Found */
            message: string;
            /** @example Not Found */
            error?: string;
          };
        };
      };
    };
  };
  AuthController_signIn: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInDto"];
      };
    };
    responses: {
      /** @description User found */
      200: {
        content: {
          "application/json": components["schemas"]["SignInResponse"];
        };
      };
      401: {
        content: {
          "application/json": {
            /** @example 401 */
            statusCode: number;
            /** @example Unauthorized */
            message: string;
            /** @example Unauthorized */
            error?: string;
          };
        };
      };
    };
  };
  MyListController_getMyList: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MyListItemDto"][];
        };
      };
    };
  };
  MyListController_addToMyList: {
    parameters: {
      path: {
        tmdbId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MyListItemDto"][];
        };
      };
    };
  };
  MyListController_removeFromMyList: {
    parameters: {
      path: {
        tmdbId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MyListItemDto"][];
        };
      };
    };
  };
  TitlesController_getLibrary: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TitleDto"][];
        };
      };
    };
  };
  TitlesController_getContinueWatching: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ContinueWatchingDto"][];
        };
      };
    };
  };
  TitlesController_getTitle: {
    parameters: {
      query: {
        type: "movie" | "series";
      };
      path: {
        tmdbId: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TitleDto"];
        };
      };
    };
  };
  TitlesController_updateTitle: {
    parameters: {
      query: {
        type: "movie" | "series";
      };
      path: {
        tmdbId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTitleDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TitleDto"];
        };
      };
    };
  };
  TitlesController_updateProgress: {
    parameters: {
      query: {
        type: "movie" | "series";
      };
      path: {
        tmdbId: number;
        season: number;
        episode: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProgressDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TitleDto"];
        };
      };
    };
  };
  AppController_getHello: {
    responses: {
      200: {
        content: never;
      };
    };
  };
}
